### ISSUE TITLE
Readme confusion

### ISSUE THREAD

**Issue by PromoFaux** [ProgrammerDan/civcraft-vm#3]
Just remembered I came across an issue with this line in he readme when I first tried to follow it:

> .7. Clone this repository locally: <code>git clone git@github.com:ProgrammerDan/civcraft-vm.git</code>

running that command was giving the following output:

```
Cloning into 'civcraft-vm'
Warning: Permanently added <blah blah blah>
Permission denied (publickey).
fatal: could not read from the remote repository.
```

what worked for me was to run:

```
git clone https://github.com/ProgrammerDan/civcraft-vm
```

**Comment by ProgrammerDan** [comment]
Ah, I'll add both forms to the readme. The git@ version requires you to have an SSH key in your github profile; the HTTPS version does not.

**Comment by PromoFaux** [comment]
Yeah, as I said the other night, I'm quite new to git!

**Comment by PromoFaux** [comment]
Oh actually, on a simlar note:

> . 10 SSH into vagrant: <code>vagrant@127.0.0.1:2222</code> default password <code>vagrant</code>

I could not ssh in that way through git bash. I had to type:

```
ssh vagrant@127.0.0.1 -p 2222
```

**Comment by ProgrammerDan** [comment]
Yeah, I should make that line _more_ general. I use putty myself, others use Kitty, others still command line SSH ... :) Good catch!

**Comment by PromoFaux** [comment]
If the idea is to have an bulletproof setup that even the most novice of users can understand, then I think that might be a good idea! Expect more annoying proof-reading pointers ;)

**Comment by ProgrammerDan** [comment]
:D Keep 'em coming. 

In terms of target, it's the "inexperienced yet eager" crowd. Not dead novice, not super elite, but the spectrum in between. Folks that don't mind putting a little effort in, but the steep wall of "do it yourself" keeps them from even starting.
