### ISSUE TITLE
./spigot/craftbukkit-pom.xml not created on build

### ISSUE THREAD

**Issue by PromoFaux** [ProgrammerDan/civcraft-vm#4]
See title.  'Spigot-pom.xml' is created fine.

**Comment by ProgrammerDan** [comment]
Hum, thanks. I'll look into it.

**Comment by PromoFaux** [comment]
I think it's making one on the vm, and adding it to the maven repository there, but on the host file system it's not in the spigot folder.

**Comment by ProgrammerDan** [comment]
I don't think I'm using those faux pom files any more anyway. I think it would suffice to simply duplicate the command string I reference to install the other jars, for the Craftbukkit jar.

**Comment by PromoFaux** [comment]
I guess this project is dead in the water now that 2.0 is dead.

Are we likely to see anything similar for 3.0?
