### ISSUE TITLE
Still usable?

### ISSUE THREAD

**Issue by jjj5311** [ProgrammerDan/civcraft-vm#5]
Is this suitable for civcraft current setup? Been out of it for a few months so not sure if this will cover everything or even work?

**Comment by ProgrammerDan** [comment]
Ah, it needs some upgrades. Its bones are good.

I recently provisioned a real server from ground up though, I should update this while that knowledge is fresh.

**Comment by jjj5311** [comment]
ok, i will do the old manual setup in the mean time

**Comment by ProgrammerDan** [comment]
You should be safe to use this as a base

Just once its done provisioning, go in and rebuild using --rev 1.8.7 on Spigot. 

Actually I could make that change quick...

**Comment by jjj5311** [comment]
ah okay i will do that then

**Comment by ProgrammerDan** [comment]
Alright, it's good to use. At least keeps your dev stuff contained on a VM, which is helpful.
